// src/components/ProjectModal.tsx
import Carousel from 'react-bootstrap/Carousel';
import Modal from 'react-bootstrap/Modal';
import type { Project } from '../data/Project';

type ProjectModalProps = {
  project: Project | null;
  show: boolean;
  onHide: () => void;
};

export default function ProjectModal({ project, show, onHide }: ProjectModalProps): JSX.Element | null {
  if (project === null) {
    return null;
  }

  return (
    <Modal show={show} onHide={onHide} size="lg">
      <Modal.Header closeButton>
        <h2 style={{ margin: 0 }}>{project.name}</h2>
      </Modal.Header>
      <Modal.Body>
        <Carousel interval={null}>
          {project.pictures.map((picture: string, index: number) => (
            <Carousel.Item key={`${picture}-${index}`}>
              <img src={picture} alt="slide" style={{ display: 'block', width: '100%' }} />
            </Carousel.Item>
          ))}
        </Carousel>
        <h3 className="mt-2">Description</h3>
        <p>{project.description}</p>
        <p>
          You can find this project on GitHub{' '}
          <a href={project.projectLink} target="_blank" rel="noreferrer">
            here
          </a>
        </p>
        <hr />
        <div className="d-flex flex-wrap">
          {project.tags.map((tag) => (
            <div key={tag.key} className="tag me-2 mb-1" style={{ backgroundColor: tag.color }}>
              {tag.key}
            </div>
          ))}
        </div>
      </Modal.Body>
    </Modal>
  );
}

// src/app/project-modal/project-modal.component.ts
import { Component } from '@angular/core';
import { BsModalRef } from 'ngx-bootstrap/modal';
import { Project } from '../_models/Project';

@Component({
  selector: 'app-project-modal',
  templateUrl: './project-modal.component.html',
  styleUrls: ['./project-modal.component.css'],
})
export class ProjectModalComponent {

  project = {} as Project;

  constructor(public bsModalRef: BsModalRef) {}
}

<div class="modal-header">
  <h2>{{project.name}}</h2>
  <button class="btn-close" (click)="bsModalRef.hide()"></button>
</div>
<div class="modal-body">
  <carousel>
    <div *ngFor="let picture of project.pictures">
      <slide><img src={{picture}} alt="slide" style="display: block; width: 100%;"></slide>
    </div>
  </carousel>
  <h3 class="mt-2">Description</h3>
  <p>{{project.description}}</p>
  <p>You can find this project on GitHub <a href={{project.projectLink}} target="_blank">here</a></p>
  <hr>
  <div class="d-flex flex-wrap">
    <div *ngFor="let tag of project.tags">
      <div class="tag me-2 mb-1" [style.background-color]="tag.color">{{tag}}</div>
    </div>
  </div>
</div>
