// src/app/project-card/project-card.component.ts
import { Component, Input } from '@angular/core';
import { Project } from '../_models/Project';

@Component({
  selector: 'app-project-card',
  templateUrl: './project-card.component.html',
  styleUrls: ['./project-card.component.css'],
})
export class ProjectCardComponent {
  @Input() project = {} as Project;
}

<div class="card shadow text-center" style="max-width: 350px; min-width: 350px;">
  <div class="card-body">
    <h5 class="card-title">{{project.name}}</h5>
    <p class="card-text">{{project.summary}}</p>
    <button class="btn btn-primary" (click)="openProjectModal()">View More</button>
  </div>

  <div class="card-footer">
    <div class="d-flex flex-wrap justify-content-center">
      <div *ngFor="let tag of project.tags">
        <div class="tag me-2 mb-1" [style.background-color]="tag.color">{{tag}}</div>
      </div>
    </div>
  </div>
</div>

// src/components/ProjectCard.tsx
import type { Project } from '../data/Project';

type ProjectCardProps = {
  project: Project;
  onViewMore: () => void;
};

export default function ProjectCard({ project, onViewMore }: ProjectCardProps): JSX.Element {
  return (
    <div className="card shadow text-center" style={{ maxWidth: 350, minWidth: 350 }}>
      <div className="card-body">
        <h5 className="card-title">{project.name}</h5>
        <p className="card-text">{project.summary}</p>
        <button className="btn btn-primary" onClick={onViewMore}>
          View More
        </button>
      </div>

      <div className="card-footer">
        <div className="d-flex flex-wrap justify-content-center">
          {project.tags.map((tag) => (
            <div key={tag.key} className="tag me-2 mb-1" style={{ backgroundColor: tag.color }}>
              {tag.key}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
